<?php
return [
    'default_language' => 'ar',
    'rtl' => 'false',
    'primary_color' => '#007bff',
    'min_php_version' => '8.0',
    'required_extensions' => ['mysqli', 'json', 'mbstring'],
    'translations' => [
        'ar' => [
            'welcome' => 'مرحبًا بك في تثبيت النظام',
            'step' => 'خطوة',
            'check_requirements' => 'التحقق من متطلبات النظام',
            'check_requirements_txt' => 'php 8.0<br>extension mysqli, json, mbstring',
            'db_config' => 'إعداد قاعدة البيانات',
            'run_sql' => 'تهيئة قاعدة البيانات',
            'run_sql_txt' => 'تهيئة الجداول والبيانات الاساسية',
            'update_config' => 'تعديل ملف الإعدادات',
            'update_config_txt' => 'تهيئة ملف الاعدادات للنظام',
            'installation_success' => 'تم تثبيت النظام بنجاح!',
            'installation_success_txt' => 'user : admin <br> password : admin',
            'next' => 'التالي >',
            'finish' => 'إنهاء',
            'php_version_error' => 'إصدار PHP الحالي أقل من المطلوب.',
            'extension_error' => 'امتداد :extension غير مفعّل. يرجى تفعيله.',
            'db_connection_error' => 'فشل الاتصال بقاعدة البيانات: :error',
            'db_host' => 'الهوست',
            'db_name' => 'قاعدة البيانات',
            'db_user' => 'اسم المستخدم',
            'db_pass' => 'كلمة المرور',

        ],
        'en' => [
            'welcome' => 'Welcome to install the system',
            'step' => 'Step',
            'check_requirements' => 'Check system requirements',
            'check_requirements_txt' => 'php 8.0<br>extension mysqli, json, mbstring',
            'db_config' => 'Database Setting',
            'run_sql' => 'Initialize the database',
            'run_sql_txt' => 'Preparing tables and basic data',
            'update_config' => 'Modify the settings file',
            'update_config_txt' => 'Initialize the system settings file',
            'installation_success' => 'The system has been installed successfully!',
            'installation_success_txt' => 'user : admin <br> password : admin',
            'next' => 'Next >',
            'finish' => 'Finish',
            'php_version_error' => 'The current PHP version is less than desired.',
            'extension_error' => 'Extension :extension is not enabled. Please activate it.',
            'db_connection_error' => 'Database connection failed: :error',
            'db_host' => 'Host',
            'db_name' => 'Database',
            'db_user' => 'UserName',
            'db_pass' => 'Password',
        ],
    ],
];
